# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=40, unique=True)),
                ('author', models.CharField(max_length=40)),
                ('code', models.TextField()),
                ('comment', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('phone_num', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=32)),
                ('role_code', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('gender', models.BooleanField(default=1)),
            ],
        ),
    ]
